"""Shell completions, generated from the argument parser rather than hand-maintained.

Hand-written completion files go stale the moment a flag is added; these are printed from
`build_parser()` itself, so a new subcommand or option shows up in the completions for free.
The Arch package generates them at build time and installs the files.

    wpt completions fish     # ~/.config/fish/completions/wpt.fish
    wpt completions bash     # /usr/share/bash-completion/completions/wpt
    wpt completions zsh      # /usr/share/zsh/site-functions/_wpt
"""

from __future__ import annotations

import argparse

SHELLS = ("fish", "bash", "zsh")


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _flags(parser: argparse.ArgumentParser) -> list[str]:
    """Long options for one (sub)command, positional-free."""
    found: list[str] = []
    for action in parser._actions:
        for option in action.option_strings:
            if option.startswith("--"):
                found.append(option)
    return sorted(set(found))


def _takes_value(parser: argparse.ArgumentParser) -> set[str]:
    """Options that expect an argument (so fish/bash should not offer files blindly)."""
    wants: set[str] = set()
    for action in parser._actions:
        if action.nargs == 0 or isinstance(action, (argparse._StoreTrueAction, argparse._StoreFalseAction,
                                                    argparse._CountAction, argparse._HelpAction,
                                                    argparse._VersionAction)):
            continue
        for option in action.option_strings:
            if option.startswith("--"):
                wants.add(option)
    return wants


def fish(parser: argparse.ArgumentParser, program: str = "wpt") -> str:
    lines = [
        "# fish completions for wpt - generated by 'wpt completions fish'",
        "# install: wpt completions fish > ~/.config/fish/completions/wpt.fish",
        f"complete -c {program} -f",
    ]
    subcommands = _subparsers(parser)
    for command in sorted(subcommands):
        lines.append(f"complete -c {program} -n '__fish_use_subcommand' -a {command}")
    for option in _flags(parser):
        if option in ("--help", "--version"):
            continue
        lines.append(f"complete -c {program} -n '__fish_use_subcommand' -l {option[2:]}")
    for command, sub in sorted(subcommands.items()):
        lines.append("")
        lines.append(f"# {command}")
        for option in _flags(sub):
            if option == "--help":
                continue
            needs_value = option in _takes_value(sub)
            suffix = " -r" if needs_value else ""
            lines.append(
                f"complete -c {program} -n '__fish_seen_subcommand_from {command}' -l {option[2:]}{suffix}"
            )
    return "\n".join(lines) + "\n"


def bash(parser: argparse.ArgumentParser, program: str = "wpt") -> str:
    subcommands = _subparsers(parser)
    cases = []
    for command, sub in sorted(subcommands.items()):
        options = " ".join(o for o in _flags(sub) if o != "--help")
        cases.append(f"        {command})\n            opts=\"{options}\"\n            ;;")
    return f"""# bash completions for wpt - generated by 'wpt completions bash'
# install: wpt completions bash | sudo tee /usr/share/bash-completion/completions/wpt
_wpt() {{
    local cur prev commands opts
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    commands="{" ".join(sorted(subcommands))}"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    case "${{COMP_WORDS[1]}}" in
{chr(10).join(cases)}
        *)
            opts="--help"
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return 0
    fi
    COMPREPLY=( $(compgen -f -- "$cur") )
    return 0
}}
complete -F _wpt {program}
"""


def zsh(parser: argparse.ArgumentParser, program: str = "wpt") -> str:
    subcommands = _subparsers(parser)
    lines = [
        f"#compdef {program}",
        f"# zsh completions for wpt - generated by 'wpt completions zsh'",
        f"# install: wpt completions zsh | sudo tee /usr/share/zsh/site-functions/_{program}",
        "",
        f"_{program}() {{",
        "    local -a commands",
        "    commands=(",
    ]
    for command, sub in sorted(subcommands.items()):
        description = (sub.description or "").replace("'", "")
        lines.append(f"        '{command}:{description}'")
    lines += [
        "    )",
        "    if (( CURRENT == 2 )); then",
        "        _describe 'command' commands",
        "        return",
        "    fi",
        "    local -a opts",
        "    opts=(",
    ]
    for command, sub in sorted(subcommands.items()):
        options = " ".join(o for o in _flags(sub) if o != "--help")
        lines.append(f"        '{command}:{options}'")
    lines += [
        "    )",
        "    _describe 'option' opts",
        "}",
        "",
        f"_{program} \"$@\"",
    ]
    return "\n".join(lines) + "\n"


def generate(shell: str, parser: argparse.ArgumentParser, program: str = "wpt") -> str:
    shell = shell.strip().lower()
    if shell == "fish":
        return fish(parser, program)
    if shell == "bash":
        return bash(parser, program)
    if shell == "zsh":
        return zsh(parser, program)
    raise ValueError(f"unknown shell '{shell}' - try one of: {', '.join(SHELLS)}")
